# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
author: "Lane Schwartz"
title: Research
email: lanes@illinois.edu
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
#baseurl: "/lanes" # the subpath of your site, e.g. /blog
lang: "en"
url: "https://computational.linguistics.illinois.edu" # the base hostname & protocol for your site
orcid: "0000-0003-2609-8133"
github:  dowobeha
googleplus: dowobeha
googlescholar: J8a1zEwAAAAJ
linkedin: "lane-schwartz-96093b8"
youtube: "UCvL-WYGy1IrlKppd-UdCkcg"
phone: "+1-217-300-0989"

# Build settings
markdown: kramdown
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"

# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  sass_dir: assets/_sass
  style: compressed


images: '/assets/images'
